services:
  spring_db:
    image: mysql:8.0
    container_name: spring_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p\"$${MYSQL_ROOT_PASSWORD}\""
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s
    restart: unless-stopped
    networks:
      - employee_network

  spring_employee:
    profiles:
      - docker-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_employee
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Tokyo
    depends_on:
      spring_db:
        condition: service_healthy
    restart: "no"
    networks:
      - employee_network

volumes:
  mysql-data:

networks:
  employee_network:
    driver: bridge