CREATE TABLE projects (
    project_id BIGINT NOT NULL AUTO_INCREMENT,
    project_no VARCHAR(10) NOT NULL,
    client_id BIGINT NOT NULL,
    project_name VARCHAR(200) NOT NULL,
    project_summary TEXT NOT NULL,
    industry_code CHAR(2) NULL,
    work_location VARCHAR(200) NOT NULL,
    nearest_station VARCHAR(100) NULL,
    remote_type CHAR(2) NOT NULL,
    planned_start_date DATE NOT NULL,
    planned_end_date DATE NULL,
    headcount INT NOT NULL,
    unit_price DECIMAL(12, 0) NULL,
    commercial_flow VARCHAR(200) NULL,
    interview_count TINYINT NULL,
    project_status CHAR(2) NOT NULL,
    sales_user_id BIGINT NOT NULL,
    remarks VARCHAR(1000) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (project_id),
    CONSTRAINT uk_projects_project_no UNIQUE (project_no),
    CONSTRAINT fk_projects_client FOREIGN KEY (client_id) REFERENCES clients (client_id),
    CONSTRAINT fk_projects_sales_user FOREIGN KEY (sales_user_id) REFERENCES users (user_id),
    CONSTRAINT ck_projects_period CHECK (planned_end_date IS NULL OR planned_end_date >= planned_start_date),
    CONSTRAINT ck_projects_headcount CHECK (headcount >= 1),
    CONSTRAINT ck_projects_unit_price CHECK (unit_price IS NULL OR unit_price >= 0),
    CONSTRAINT ck_projects_interview_count CHECK (interview_count IS NULL OR interview_count >= 0),
    INDEX ix_projects_search (project_status, sales_user_id, planned_start_date, deleted_at),
    INDEX ix_projects_client (client_id),
    INDEX ix_projects_station (nearest_station),
    INDEX ix_projects_industry (industry_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE project_skills (
    project_skill_id BIGINT NOT NULL AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,
    requirement_type CHAR(1) NOT NULL,
    required_months INT NULL,
    required_level TINYINT NULL,
    remarks VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (project_skill_id),
    CONSTRAINT uk_project_skills UNIQUE (project_id, skill_id, requirement_type),
    CONSTRAINT fk_project_skills_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_project_skills_skill FOREIGN KEY (skill_id) REFERENCES skills (skill_id),
    CONSTRAINT ck_project_skills_type CHECK (requirement_type IN ('1', '2')),
    CONSTRAINT ck_project_skills_months CHECK (required_months IS NULL OR required_months >= 0),
    CONSTRAINT ck_project_skills_level CHECK (required_level IS NULL OR required_level BETWEEN 1 AND 5),
    INDEX ix_project_skills_skill (skill_id, requirement_type, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE assignments (
    assignment_id BIGINT NOT NULL AUTO_INCREMENT,
    employee_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    contract_start_date DATE NOT NULL,
    contract_end_date DATE NULL,
    assignment_status CHAR(2) NOT NULL,
    role_name VARCHAR(100) NULL,
    processes VARCHAR(200) NULL,
    remarks VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by BIGINT NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (assignment_id),
    CONSTRAINT fk_assignments_employee FOREIGN KEY (employee_id) REFERENCES employees (employee_id),
    CONSTRAINT fk_assignments_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT ck_assignments_period CHECK (contract_end_date IS NULL OR contract_end_date >= contract_start_date),
    INDEX ix_assignments_employee (employee_id, assignment_status, deleted_at),
    INDEX ix_assignments_project (project_id, assignment_status, deleted_at),
    INDEX ix_assignments_end (assignment_status, contract_end_date, deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
