-- Additional scheduled interviews for dashboard pagination verification.
-- V6 inserts eight future scheduled interviews. These four rows bring the
-- total to twelve, producing ten rows on page 1 and two rows on page 2.

INSERT INTO interviews (
    employee_id,
    project_id,
    interview_datetime,
    duration_minutes,
    interview_type,
    location_url,
    sales_user_id,
    interview_status,
    interview_result,
    sales_comment,
    next_action,
    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES
    (
        (SELECT employee_id FROM employees WHERE employee_no = 'E000000007'),
        (SELECT project_id FROM projects WHERE project_no = 'P000000003'),
        DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 7 DAY),
        60,
        '02',
        'https://example.local/interviews/page-011',
        (SELECT user_id FROM users WHERE login_id = 'sales01'),
        '01',
        NULL,
        'ページング確認用予定11',
        '面談実施',
        CURRENT_TIMESTAMP,
        1,
        CURRENT_TIMESTAMP,
        1
    ),
    (
        (SELECT employee_id FROM employees WHERE employee_no = 'E000000008'),
        (SELECT project_id FROM projects WHERE project_no = 'P000000004'),
        DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 8 DAY),
        45,
        '01',
        '東京都渋谷区渋谷1-1',
        (SELECT user_id FROM users WHERE login_id = 'sales02'),
        '01',
        NULL,
        'ページング確認用予定12',
        '面談実施',
        CURRENT_TIMESTAMP,
        1,
        CURRENT_TIMESTAMP,
        1
    ),
    (
        (SELECT employee_id FROM employees WHERE employee_no = 'E000000009'),
        (SELECT project_id FROM projects WHERE project_no = 'P000000005'),
        DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 9 DAY),
        30,
        '03',
        '03-0000-0013',
        (SELECT user_id FROM users WHERE login_id = 'sales01'),
        '01',
        NULL,
        'ページング確認用予定13',
        '面談実施',
        CURRENT_TIMESTAMP,
        1,
        CURRENT_TIMESTAMP,
        1
    ),
    (
        (SELECT employee_id FROM employees WHERE employee_no = 'E000000010'),
        (SELECT project_id FROM projects WHERE project_no = 'P000000006'),
        DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 10 DAY),
        60,
        '02',
        'https://example.local/interviews/page-014',
        (SELECT user_id FROM users WHERE login_id = 'sales02'),
        '01',
        NULL,
        'ページング確認用予定14',
        '面談実施',
        CURRENT_TIMESTAMP,
        1,
        CURRENT_TIMESTAMP,
        1
    );
